spring.application.name=ai-agent-tools-demo

spring.ai.openai.base-url=${OPENAI_BASE_URL:https://generativelanguage.googleapis.com/v1beta/openai}
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=${OPENAI_MODEL:gemini-flash-lite-latest}

weather.api-key=${WEATHER_API_KEY}